package com.ptu.medoc.exception;

public enum ErrorCode {
    DOCTOR_NOT_FOUND,
    SLOT_NOT_FOUND,
    SLOT_FULL,
    TOKEN_NOT_FOUND,
    DUPLICATE_TOKEN,
    INVALID_TOKEN_STATE,
    WAITLIST_EMPTY,
    EMERGENCY_OVERRIDE_FAILED,
    TOKEN_ALLOCATION_FAILED,
    INTERNAL_SERVER_ERROR
}
